
// 常量要大写
// rankings_img_size
export class PlanetConstants {
  // recommended_height
  static readonly RECOMMENDED_ITEM_HEIGHT: number = 130;
  // tag_bg_color
  static readonly TAG_BG_COLOR: string = 'rgba(100, 100, 255, 0.3)';
  // rankings_item_width
  static readonly RANKINGS_ITEM_HEIGHT: number = 60;
  // rankings_img_size
  static readonly RANKINGS_IMG_SIZE: number = 40;
  // rankings_index_img_size
  static readonly RANKINGS_INDEX_IMG_SIZE: number = 28;
}
