import { Card } from './CardModel'

const cardData: Card[] = [
  {
    category_id: "1",
    id: "1",
    title: "XXXX40 Pro",
    author: "华为",
    authorImg: $r('app.media.default_author_img'),
    images: $r('app.media.default_img'),
    description: "XXXX Pro 5G手机",
    price: 6399,
    promotion: ["新品"]
  },
  {
    category_id: "1",
    id: "2",
    title: "XXXX40 Pro",
    author: "华为",
    authorImg: $r('app.media.default_author_img'),
    images: $r('app.media.default_img'),
    description: "XXXX Pro 5G手机",
    price: 6399,
    promotion: ["新品"]
  },
  {
    category_id: "1",
    id: "3",
    title: "XXXX40 Pro",
    author: "华为",
    authorImg: $r('app.media.default_author_img'),
    images: $r('app.media.default_img'),
    description: "XXXX Pro 5G手机",
    price: 6399,
    promotion: ["新品"]
  },
  {
    category_id: "1",
    id: "4",
    title: "XXXX40 Pro",
    author: "华为",
    authorImg: $r('app.media.default_author_img'),
    images: $r('app.media.default_img'),
    description: "XXXX Pro 5G手机",
    price: 6399,
    promotion: ["新品"]
  },
  {
    category_id: "1",
    id: "5",
    title: "XXXX40 Pro",
    author: "华为",
    authorImg: $r('app.media.default_author_img'),
    images: $r('app.media.default_img'),
    description: "XXXX Pro 5G手机",
    price: 6399,
    promotion: ["新品"]
  },
  // {
  //   category_id: "1",
  //   id: "6",
  //   title: "XXXX40 Pro",
  //   author: "华为",
  //   authorImg: $r('app.media.default_author_img'),
  //   images: $r('app.media.default_img'),
  //   description: "XXXX Pro 5G手机",
  //   price: 6399,
  //   promotion: ["新品"]
  // },
  // {
  //   category_id: "1",
  //   id: "7",
  //   title: "XXXX40 Pro",
  //   author: "华为",
  //   authorImg: $r('app.media.default_author_img'),
  //   images: $r('app.media.default_img'),
  //   description: "XXXX Pro 5G手机",
  //   price: 6399,
  //   promotion: ["新品"]
  // },
  // {
  //   category_id: "1",
  //   id: "8",
  //   title: "XXXX40 Pro",
  //   author: "华为",
  //   authorImg: $r('app.media.default_author_img'),
  //   images: $r('app.media.default_img'),
  //   description: "XXXX Pro 5G手机",
  //   price: 6399,
  //   promotion: ["新品"]
  // }
]

export { cardData }