import { Card1 } from './PlanetModel'

/**
 * Application simulation data can be obtained from the server by developers.
 */
const card1Data: Card1[] = [
  {
    detail: $r('app.media.default_img'),
    specifications: [
      {
        id: '颜色',
        title: '颜色',
        data: [
          { key: '深邃黑', value: '深邃黑', image: '' },
          { key: '珠光白', value: '珠光白', image: '' },
          { key: '宝石蓝', value: '宝石蓝', image: '' }
        ]
      },
      {
        id: '版本',
        title: '版本',
        data: [
          { key: '8+128G', value: '8+128G', image: '' },
          { key: '8+256G', value: '8+256G', image: '' },
          { key: '12+512G', value: '12+512G', image: '' }
        ]
      },
      {
        id: '网络制式',
        title: '网络制式',
        data: [
          { key: '4G全网通', value: '4G全网通', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      },
      {
        id: '类型',
        title: '类型',
        data: [
          { key: '官方标配', value: '官方标配', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      }
    ],
    category_id: "1",
    price: 6399,
    title: "XXXX40 Pro",
    images: $r('app.media.default_img'),
    id: "1",
    description: "XXXX Pro 5G手机",
    promotion: "新品"
  },
  {
    detail: ["common/product002.png"],
    specifications: [
      {
        id: '颜色',
        title: '颜色',
        data: [
          { key: '深邃黑', value: '深邃黑', image: '' },
          { key: '珠光白', value: '珠光白', image: '' },
          { key: '宝石蓝', value: '宝石蓝', image: '' }
        ]
      },
      {
        id: '版本',
        title: '版本',
        data: [
          { key: '8+128G', value: '8+128G', image: '' },
          { key: '8+256G', value: '8+256G', image: '' },
          { key: '12+512G', value: '12+512G', image: '' }
        ]
      },
      {
        id: '网络制式',
        title: '网络制式',
        data: [
          { key: '4G全网通', value: '4G全网通', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      },
      {
        id: '类型',
        title: '类型',
        data: [
          { key: '官方标配', value: '官方标配', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      }
    ],
    category_id: "1",
    price: 5199,
    title: "XXXXBook 13",
    images: ["common/product002.png"],
    id: "2",
    description: "XX笔记本电脑XXXXBook 13 11代酷睿",
    promotion: "新品"
  },
  {
    detail: ["common/product003.png"],
    specifications: [
      {
        id: '颜色',
        title: '颜色',
        data: [
          { key: '黑色', value: '黑色', image: '' },
          { key: '白色', value: '白色', image: '' }
        ]
      },
      {
        id: '版本',
        title: '版本',
        data: [
          { key: '8+128G', value: '8+128G', image: '' },
          { key: '8+256G', value: '8+256G', image: '' },
          { key: '12+512G', value: '12+512G', image: '' }
        ]
      },
      {
        id: '网络制式',
        title: '网络制式',
        data: [
          { key: '4G全网通', value: '4G全网通', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      },
      {
        id: '类型',
        title: '类型',
        data: [
          { key: '官方标配', value: '官方标配', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      }
    ],
    category_id: "3",
    price: 6588,
    title: "PXX40 Pro",
    images: ["common/product003.png"],
    id: "3",
    description: "PXX40 Pro 5G手机 支持XXXOS",
    promotion: "限时"
  },
  {
    detail: ["common/product004.png"],
    specifications: [
      {
        id: '颜色',
        title: '颜色',
        data: [
          { key: '深邃黑', value: '深邃黑', image: '' },
          { key: '珠光白', value: '珠光白', image: '' },
          { key: '宝石蓝', value: '宝石蓝', image: '' }
        ]
      },
      {
        id: '版本',
        title: '版本',
        data: [
          { key: '8+128G', value: '8+128G', image: '' },
          { key: '8+256G', value: '8+256G', image: '' },
          { key: '12+512G', value: '12+512G', image: '' }
        ]
      },
      {
        id: '网络制式',
        title: '网络制式',
        data: [
          { key: '4G全网通', value: '4G全网通', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      },
      {
        id: '类型',
        title: '类型',
        data: [
          { key: '官方标配', value: '官方标配', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      }
    ],
    category_id: '',
    price: 3999,
    title: "XXXX30 Pro",
    images: ["common/product004.png"],
    id: "4",
    description: "XXXX30 Pro 超长续航 支持XXXOS系统",
    promotion: "新品"
  },
  {
    detail: ["common/product005.png"],
    specifications: [
      {
        id: '颜色',
        title: '颜色',
        data: [
          { key: '黑色', value: '黑色', image: '' },
          { key: '白色', value: '白色', image: '' }
        ]
      },
      {
        id: '版本',
        title: '版本',
        data: [
          { key: '8+128G', value: '8+128G', image: '' },
          { key: '8+256G', value: '8+256G', image: '' },
          { key: '12+512G', value: '12+512G', image: '' }
        ]
      },
      {
        id: '网络制式',
        title: '网络制式',
        data: [
          { key: '4G全网通', value: '4G全网通', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      },
      {
        id: '类型',
        title: '类型',
        data: [
          { key: '官方标配', value: '官方标配', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      }
    ],
    category_id: '',
    price: 1899,
    title: "XX20e",
    images: ["common/product005.png"],
    id: "5",
    description: "XX 5000mAh大电池 6.3英寸高清大屏",
    promotion: "赠送积分"
  },
  {
    detail: ["common/product006.png"],
    specifications: [
      {
        id: '颜色',
        title: '颜色',
        data: [
          { key: '深邃黑', value: '深邃黑', image: '' },
          { key: '珠光白', value: '珠光白', image: '' },
          { key: '宝石蓝', value: '宝石蓝', image: '' }
        ]
      },
      {
        id: '版本',
        title: '版本',
        data: [
          { key: '8+128G', value: '8+128G', image: '' },
          { key: '8+256G', value: '8+256G', image: '' },
          { key: '12+512G', value: '12+512G', image: '' }
        ]
      },
      {
        id: '网络制式',
        title: '网络制式',
        data: [
          { key: '4G全网通', value: '4G全网通', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      },
      {
        id: '类型',
        title: '类型',
        data: [
          { key: '官方标配', value: '官方标配', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      }
    ],
    category_id: '',
    price: 2199,
    title: "XX20 Plus",
    images: ["common/product006.png"],
    id: "6",
    description: "40W超级快充 90Hz高刷新率",
    promotion: "新品"
  },
  {
    detail: ["common/product006.png"],
    specifications: [
      {
        id: '颜色',
        title: '颜色',
        data: [
          { key: '黑色', value: '黑色', image: '' },
          { key: '白色', value: '白色', image: '' }
        ]
      },
      {
        id: '版本',
        title: '版本',
        data: [
          { key: '8+128G', value: '8+128G', image: '' },
          { key: '8+256G', value: '8+256G', image: '' },
          { key: '12+512G', value: '12+512G', image: '' }
        ]
      },
      {
        id: '网络制式',
        title: '网络制式',
        data: [
          { key: '4G全网通', value: '4G全网通', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      },
      {
        id: '类型',
        title: '类型',
        data: [
          { key: '官方标配', value: '官方标配', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      }
    ],
    category_id: "1",
    price: 3299,
    title: "XXXX7 Pro",
    images: ["common/product006.png"],
    id: "7",
    description: "XX手机 5000W高清后置拍摄",
    promotion: "限时"
  },
  {
    detail: ["common/product006.png"],
    specifications: [
      {
        id: '颜色',
        title: '颜色',
        data: [
          { key: '深邃黑', value: '深邃黑', image: '' },
          { key: '珠光白', value: '珠光白', image: '' },
          { key: '宝石蓝', value: '宝石蓝', image: '' }
        ]
      },
      {
        id: '版本',
        title: '版本',
        data: [
          { key: '8+128G', value: '8+128G', image: '' },
          { key: '8+256G', value: '8+256G', image: '' },
          { key: '12+512G', value: '12+512G', image: '' }
        ]
      },
      {
        id: '网络制式',
        title: '网络制式',
        data: [
          { key: '4G全网通', value: '4G全网通', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      },
      {
        id: '类型',
        title: '类型',
        data: [
          { key: '官方标配', value: '官方标配', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      }
    ],
    category_id: "1",
    price: 12999,
    title: "XXXX xs2",
    images: ["common/product006.png"],
    id: "8",
    description: "XX曲面屏手机 内翻铰链设计",
    promotion: "赠送积分"
  },
  {
    detail: ["common/product003.png"],
    specifications: [
      {
        id: '颜色',
        title: '颜色',
        data: [
          { key: '黑色', value: '黑色', image: '' },
          { key: '白色', value: '白色', image: '' }
        ]
      },
      {
        id: '版本',
        title: '版本',
        data: [
          { key: '8+128G', value: '8+128G', image: '' },
          { key: '8+256G', value: '8+256G', image: '' },
          { key: '12+512G', value: '12+512G', image: '' }
        ]
      },
      {
        id: '网络制式',
        title: '网络制式',
        data: [
          { key: '4G全网通', value: '4G全网通', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      },
      {
        id: '类型',
        title: '类型',
        data: [
          { key: '官方标配', value: '官方标配', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      }
    ],
    category_id: "3",
    price: 6588,
    title: "PXX40 Pro",
    images: ["common/product003.png"],
    id: "9",
    description: "PXX40 Pro 5G手机 支持XXXOS",
    promotion: "限时"
  },
  {
    detail: ["common/product004.png"],
    specifications: [
      {
        id: '颜色',
        title: '颜色',
        data: [
          { key: '深邃黑', value: '深邃黑', image: '' },
          { key: '珠光白', value: '珠光白', image: '' },
          { key: '宝石蓝', value: '宝石蓝', image: '' }
        ]
      },
      {
        id: '版本',
        title: '版本',
        data: [
          { key: '8+128G', value: '8+128G', image: '' },
          { key: '8+256G', value: '8+256G', image: '' },
          { key: '12+512G', value: '12+512G', image: '' }
        ]
      },
      {
        id: '网络制式',
        title: '网络制式',
        data: [
          { key: '4G全网通', value: '4G全网通', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      },
      {
        id: '类型',
        title: '类型',
        data: [
          { key: '官方标配', value: '官方标配', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      }
    ],
    category_id: '',
    price: 3999,
    title: "XXXX30 Pro",
    images: ["common/product004.png"],
    id: "10",
    description: "XXXX30 Pro 超长续航 支持XXXOS系统",
    promotion: "新品"
  },
  {
    detail: ["common/product003.png"],
    specifications: [
      {
        id: '颜色',
        title: '颜色',
        data: [
          { key: '黑色', value: '黑色', image: '' },
          { key: '白色', value: '白色', image: '' }
        ]
      },
      {
        id: '版本',
        title: '版本',
        data: [
          { key: '8+128G', value: '8+128G', image: '' },
          { key: '8+256G', value: '8+256G', image: '' },
          { key: '12+512G', value: '12+512G', image: '' }
        ]
      },
      {
        id: '网络制式',
        title: '网络制式',
        data: [
          { key: '4G全网通', value: '4G全网通', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      },
      {
        id: '类型',
        title: '类型',
        data: [
          { key: '官方标配', value: '官方标配', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      }
    ],
    category_id: "3",
    price: 6588,
    title: "PXX40 Pro",
    images: ["common/product003.png"],
    id: "11",
    description: "PXX40 Pro 5G手机 支持XXXOS",
    promotion: "限时"
  },
  {
    detail: ["common/product006.png"],
    specifications: [
      {
        id: '颜色',
        title: '颜色',
        data: [
          { key: '黑色', value: '黑色', image: '' },
          { key: '白色', value: '白色', image: '' }
        ]
      },
      {
        id: '版本',
        title: '版本',
        data: [
          { key: '8+128G', value: '8+128G', image: '' },
          { key: '8+256G', value: '8+256G', image: '' },
          { key: '12+512G', value: '12+512G', image: '' }
        ]
      },
      {
        id: '网络制式',
        title: '网络制式',
        data: [
          { key: '4G全网通', value: '4G全网通', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      },
      {
        id: '类型',
        title: '类型',
        data: [
          { key: '官方标配', value: '官方标配', image: '' },
          { key: '5G全网通', value: '5G全网通', image: '' }
        ]
      }
    ],
    category_id: "1",
    price: 3299,
    title: "XXXX7 Pro",
    images: ["common/product006.png"],
    id: "12",
    description: "XX手机 5000W高清后置拍摄",
    promotion: "限时"
  }
]

export { card1Data }