/**
 * Data returned by the network request.
 */
export class ResponseResult {
  /**
   * Code returned by the network request: success, fail.
   */
  code: string;

  /**
   * Message returned by the network request.
   */
  msg: string | Resource;

  /**
   * Data returned by the network request.
   */
  data: string | Object | ArrayBuffer;

  constructor() {
    this.code = '';
    this.msg = '';
    this.data = '';
  }

  // 输出
  toString(): string {
    return `ResponseResult { code: ${this.code}, msg: ${this.msg}, data: ${this.data} }`;
  }
}